import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import ManualHeader from "../components/ManualHeader";

const Home: NextPage = () => {
    return (
        <div className="mx-auto max-w-6xl">
            <Head>
                <title>Decentralized Lottery</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="">
                {/* <ManualHeader /> */}
                <Header />
            </header>
            <main>
                <LotteryEntrance />
            </main>
        </div>
    );
};

export default Home;
